# Generated by Django 5.2.13 on 2026-05-06 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0001_initial'),
        ('tickets', '0004_chamado_resolvido_em_chamado_resolvido_por_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='equipamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chamados', to='equipamentos.equipamento'),
        ),
    ]
