# Generated by Django 5.2.13 on 2026-05-06 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0001_initial'),
        ('tickets', '0005_chamado_equipamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamado',
            name='equipamento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='chamados', to='equipamentos.equipamento'),
            preserve_default=False,
        ),
    ]
