# Generated by Django 5.2.14 on 2026-05-15 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_alter_chamado_equipamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamado',
            name='solucao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
