# Generated by Django 5.2.14 on 2026-05-19 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificacao',
            name='chamado_id',
        ),
        migrations.AddField(
            model_name='notificacao',
            name='link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='tipo',
            field=models.CharField(choices=[('NOVO_CHAMADO', 'Novo Chamado'), ('STATUS_ALTERADO', 'Status Alterado'), ('CHAMADO_RESOLVIDO', 'Chamado Resolvido'), ('ATRIBUICAO', 'Atribuição'), ('NOVO_COMENTARIO', 'Novo Comentário')], max_length=30),
        ),
    ]
