# Generated by Django 5.2.13 on 2026-05-06 13:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patrimonio', models.CharField(blank=True, editable=False, max_length=20, unique=True)),
                ('tipo', models.CharField(choices=[('DESKTOP', 'Desktop'), ('NOTEBOOK', 'Notebook'), ('SERVIDOR', 'Servidor'), ('MONITOR', 'Monitor'), ('IMPRESSORA', 'Impressora'), ('OUTRO', 'Outro')], default='DESKTOP', max_length=20)),
                ('cpu', models.CharField(blank=True, max_length=200, null=True)),
                ('memoria', models.CharField(blank=True, max_length=100, null=True)),
                ('placa_mae', models.CharField(blank=True, max_length=200, null=True)),
                ('espaco_hd', models.CharField(blank=True, max_length=100, null=True)),
                ('modelo', models.CharField(blank=True, max_length=200, null=True)),
                ('fabricante', models.CharField(blank=True, max_length=200, null=True)),
                ('numero_serie', models.CharField(blank=True, max_length=100, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipamentos_criados', to=settings.AUTH_USER_MODEL)),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipamentos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['patrimonio'],
            },
        ),
    ]
